#!/bin/bash
#
# Perform necessary puppet setup steps
# after package is installed.
#

PROGNAME=$(basename $0)
INSTALLER_DIR="/opt/puppet"
PREFIX="/usr"

function error_exit
{
  echo "${PROGNAME}: ${1:-"Unknown Error"}" 1>&2
  exit 1
}

# rm -f before ln -sf is required for solaris 9
rm -f $PREFIX/bin/puppet
rm -f $PREFIX/bin/facter

ln -sf $INSTALLER_DIR/bin/puppet $PREFIX/bin || error_exit "Cannot link puppet to $PREFIX/bin"
ln -sf $INSTALLER_DIR/bin/facter $PREFIX/bin || error_exit "Cannot link facter to $PREFIX/bin"

echo "Thank you for installing Puppet!"

exit 0
